// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Sapphire2026.Data;

#nullable disable

namespace Sapphire2026Data.Migrations
{
	[DbContext(typeof(DataStorage))]
	[Migration("20260810120000_RemoveTimeNetTables")]
	partial class RemoveTimeNetTables
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			// Modelo actual: ver DataStorageModelSnapshot (sin TimeNet).
#pragma warning restore 612, 618
		}
	}
}
