// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sapphire2026.Data;

#nullable disable

namespace Sapphire2026Data.Migrations
{
    [DbContext(typeof(DataStorage))]
    [Migration("20260622130351_GMaoBasic4")]
    partial class GMaoBasic4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sapphire2026.Data.Models.ActiveSessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("Credentials")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HostIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("HostPort")
                        .HasColumnType("int unsigned");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ActiveSessions");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.BotLogError", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("TimeStamp");

                    b.ToTable("BotLogError");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.ExtendedRole", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExtendedRoles");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Festive", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Date");

                    b.ToTable("Festives");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ClosureTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ClosureUser")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Parent")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.OwnerRegister", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.ToTable("OwnerRegister");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Register", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("Register");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.RoleDictionary", b =>
                {
                    b.Property<uint>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("RoleDictionary");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.SessionEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("eventType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("hostPoint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("timeSpan")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SessionEvents");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.StatusChange", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("mvarOperationId")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Guid");

                    b.ToTable("StatusChanges");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.TimeCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("Key")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TimeCache");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Train", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GmaoId")
                        .HasColumnType("int");

                    b.Property<byte>("LastStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("LastWash")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameCloud")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<Guid>("lastChange")
                        .HasColumnType("char(36)");

                    b.HasKey("Guid");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.ExpertAgentListRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("ExpertAgentListRecord");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.ExpertAgentsListView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<bool>("Final")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExpertAgentsListView");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.WorkShiftContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("Begin")
                        .HasColumnType("time(6)");

                    b.Property<byte>("ContentType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Discrectional")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<bool>("Foreign")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("Parent")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParentCollection")
                        .HasColumnType("char(36)");

                    b.Property<string>("TrainId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WorkShiftContent");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.WorkShiftTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Att")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BgColor")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("CoorX")
                        .HasColumnType("int");

                    b.Property<int>("CoorY")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Parent")
                        .HasColumnType("char(36)");

                    b.Property<byte>("PerWeek")
                        .HasColumnType("tinyint unsigned");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("StripeColor")
                        .HasColumnType("longtext");

                    b.Property<string>("Tokens")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WorkShiftTemplate");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.WorkShiftTemplateCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Begin")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Collective")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Include")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Owner")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("WorkShiftTemplateCollection");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.WorkshiftAssignation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Agent")
                        .HasColumnType("char(36)");

                    b.Property<string>("Annotation")
                        .HasColumnType("longtext");

                    b.Property<string>("Assignation")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Definitive")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsTD")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SwappingAgent")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("WorkShiftAssignation");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortPhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("TelegramEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramRules")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UserEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.UserAndRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("RoleId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserAndRole");
                });

            modelBuilder.Entity("Sapphire2026Data.Models.GMAO.WorkCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Atomic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GMAOWorksCatalog");
                });

            modelBuilder.Entity("Sapphire2026Data.Models.GMAO.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Atomic")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CloseUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DestinationObjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OpenUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TrainId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("VerifyUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkType")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("GMAOWorkOrders");
                });

            modelBuilder.Entity("Sapphire2026Data.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("TimeNet2026.DBStorage.DBPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color0")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RautaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TNPlans", (string)null);
                });

            modelBuilder.Entity("TimeNet2026.DBStorage.DBTopoStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("HeaderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("TNTopoStorages", (string)null);
                });

            modelBuilder.Entity("TimeNet2026Data.DBStorage.DBAsimilation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AsimilationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color0")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OriginStationId")
                        .HasColumnType("int");

                    b.Property<int>("TopoStorageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TNAsimilations", (string)null);
                });

            modelBuilder.Entity("TimeNet2026Data.DBStorage.DBAsimilationStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AsimilationId")
                        .HasColumnType("int");

                    b.Property<int>("AxisId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationStationId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("stopTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("tripTime")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("TNAsimilationSteps", (string)null);
                });

            modelBuilder.Entity("TimeNet2026Data.DBStorage.DBAxis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AxisId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color0")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TNAxis", (string)null);
                });

            modelBuilder.Entity("TimeNet2026Data.DBStorage.DBCirculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<string>("Color0")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("Departure")
                        .HasColumnType("time(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TNCirculations", (string)null);
                });

            modelBuilder.Entity("TimeNet2026Data.DBStorage.DBCirculationBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AsimilationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<byte>("WeekdayMask")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("TNCirculationBlocks", (string)null);
                });

            modelBuilder.Entity("TimeNet2026Data.DBStorage.DBHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bitmap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FirstDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TNHeaders", (string)null);
                });

            modelBuilder.Entity("TimeNet2026Data.DBStorage.DBRauta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("HeaderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TopoStorageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TNRautatie", (string)null);
                });

            modelBuilder.Entity("TimeNet2026Data.DBStorage.DBRefPunctual", b =>
                {
                    b.Property<int>("AxisId")
                        .HasColumnType("int");

                    b.Property<long>("Pk")
                        .HasColumnType("bigint");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.HasKey("AxisId", "Pk");

                    b.HasIndex("AxisId");

                    b.HasIndex("Pk");

                    b.ToTable("TNRefPunctuals", (string)null);
                });

            modelBuilder.Entity("TimeNet2026Data.DBStorage.DBSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<byte>("WeekdayMask")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("TNSchedules", (string)null);
                });

            modelBuilder.Entity("TimeNet2026Data.DBStorage.DBScheduleUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("Begin")
                        .HasColumnType("time(6)");

                    b.Property<int>("CirculationId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time(6)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TNScheduleUnits", (string)null);
                });

            modelBuilder.Entity("TimeNet2026Data.DBStorage.DBStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AxisId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Pk")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TNStations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
