// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Sapphire2026.Data;

#nullable disable

namespace Sapphire2026Data.Migrations
{
	[DbContext(typeof(DataStorage))]
	[Migration("20260807160000_DiamondPublishedPlans")]
	partial class DiamondPublishedPlans
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			// See DataStorageModelSnapshot for full model.
#pragma warning restore 612, 618
		}
	}
}
