// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Sapphire2026.Data;

#nullable disable

namespace Sapphire2026Data.Migrations
{
    [DbContext(typeof(DataStorage))]
    [Migration("20260807140000_DiamondPlans")]
    partial class DiamondPlans
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // See DataStorageModelSnapshot for full model.
#pragma warning restore 612, 618
        }
    }
}