// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sapphire2026.Data;

#nullable disable

namespace Sapphire2026Data.Migrations
{
    [DbContext(typeof(DataStorage))]
    partial class DataStorageModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sapphire2026.Data.Models.ActiveSessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("Credentials")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HostIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("HostPort")
                        .HasColumnType("int unsigned");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ActiveSessions");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.BotLogError", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("TimeStamp");

                    b.ToTable("BotLogError");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Diamond.DiamondCirculationEmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CertThumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("DayLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("DocumentKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("EditionLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("EmittedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HostPoint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("PdfCmsSignatureBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PlanOrTrain")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("QrText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SealCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("SheetCount")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EmittedAtUtc");

                    b.HasIndex("SealCode");

                    b.HasIndex("UserId");

                    b.ToTable("DiamondCirculationEmissions", (string)null);
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Diamond.DiamondPlanDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IncludedTopoPath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ScriptByteLength")
                        .HasColumnType("int");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<string>("SourceScript")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TopoContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("TopoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TopoStructuralHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("IsActive");

                    b.HasIndex("TopoId");

                    b.ToTable("DiamondPlans", (string)null);
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Diamond.DiamondTemporaryLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AxisId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsNewCreation")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("Pk0")
                        .HasColumnType("bigint");

                    b.Property<long>("Pkf")
                        .HasColumnType("bigint");

                    b.Property<byte>("Reason")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("SignaledOnTrack")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<Guid>("TopoId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("Track")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("TopoId");

                    b.HasIndex("TopoId", "AxisId", "Pk0");

                    b.ToTable("DiamondTemporaryLimits", (string)null);
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Diamond.DiamondPublishedPlanDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AsimilationCount")
                        .HasColumnType("int");

                    b.Property<int>("ByteLength")
                        .HasColumnType("int");

                    b.Property<int>("CirculationCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompiledUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("mediumblob");

                    b.Property<Guid?>("SourcePlanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TopoContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("TopoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TopoStructuralHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("IsActive");

                    b.HasIndex("SourcePlanId");

                    b.HasIndex("TopoId");

                    b.HasIndex("ValidFrom");

                    b.ToTable("DiamondPublishedPlans", (string)null);
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Diamond.DiamondTopoDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("AxisCount")
                        .HasColumnType("int");

                    b.Property<int>("ByteLength")
                        .HasColumnType("int");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LayoutId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("mediumblob");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<int>("StationCount")
                        .HasColumnType("int");

                    b.Property<string>("StructuralHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("StructuralHash");

                    b.ToTable("DiamondTopos", (string)null);
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.ExtendedRole", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExtendedRoles");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Festive", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Date");

                    b.ToTable("Festives");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ClosureTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ClosureUser")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsSymptom")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MediaContentType")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("MediaExtension")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("Parent")
                        .HasColumnType("char(36)");

                    b.Property<byte>("SystemAffected")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.OwnerRegister", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.ToTable("OwnerRegister");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Register", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("Register");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.RoleDictionary", b =>
                {
                    b.Property<uint>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("RoleDictionary");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.SessionEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("eventType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("hostPoint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("timeSpan")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SessionEvents");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.StatusChange", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("mvarOperationId")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Guid");

                    b.ToTable("StatusChanges");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.TimeCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("Key")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TimeCache");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Train", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GmaoId")
                        .HasColumnType("int");

                    b.Property<long>("LastOdometer")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastOdometerSet")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastPlatformAssign")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("LastStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("LastWash")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameCloud")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<Guid>("lastChange")
                        .HasColumnType("char(36)");

                    b.HasKey("Guid");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.ExpertAgentListRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("ExpertAgentListRecord");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.ExpertAgentsListView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<bool>("Final")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExpertAgentsListView");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.WorkShiftContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("Begin")
                        .HasColumnType("time(6)");

                    b.Property<byte>("ContentType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Discrectional")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<bool>("Foreign")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("Parent")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParentCollection")
                        .HasColumnType("char(36)");

                    b.Property<string>("TrainId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WorkShiftContent");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.WorkShiftTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Att")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BgColor")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("CoorX")
                        .HasColumnType("int");

                    b.Property<int>("CoorY")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Parent")
                        .HasColumnType("char(36)");

                    b.Property<byte>("PerWeek")
                        .HasColumnType("tinyint unsigned");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("StripeColor")
                        .HasColumnType("longtext");

                    b.Property<string>("Tokens")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WorkShiftTemplate");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.WorkShiftTemplateCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Begin")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Collective")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Include")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("Owner")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("WorkShiftTemplateCollection");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Turnos.WorkshiftAssignation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Agent")
                        .HasColumnType("char(36)");

                    b.Property<string>("Annotation")
                        .HasColumnType("longtext");

                    b.Property<string>("Assignation")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Definitive")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsTD")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SwappingAgent")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("WorkShiftAssignation");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortPhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("TelegramEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramRules")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UserEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Key")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.UserAndRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("RoleId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserAndRole");
                });

            modelBuilder.Entity("Sapphire2026Data.Models.GMAO.WorkCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Atomic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GMAOWorksCatalog");
                });

            modelBuilder.Entity("Sapphire2026Data.Models.GMAO.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Atomic")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CloseUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DestinationObjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("OpenTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("OpenUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Rejected")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RequestUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TrainId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("VerifyUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkType")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("GMAOWorkOrders");
                });

            modelBuilder.Entity("Sapphire2026Data.Models.Odometry", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long>("Odometer")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeSpan")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("char(36)");

                    b.HasKey("Guid");

                    b.ToTable("Odometry");
                });

            modelBuilder.Entity("Sapphire2026Data.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Diamond.DiamondPlanDocument", b =>
                {
                    b.HasOne("Sapphire2026.Data.Models.Diamond.DiamondTopoDocument", "Topo")
                        .WithMany()
                        .HasForeignKey("TopoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topo");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Diamond.DiamondPublishedPlanDocument", b =>
                {
                    b.HasOne("Sapphire2026.Data.Models.Diamond.DiamondPlanDocument", "SourcePlan")
                        .WithMany()
                        .HasForeignKey("SourcePlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sapphire2026.Data.Models.Diamond.DiamondTopoDocument", "Topo")
                        .WithMany()
                        .HasForeignKey("TopoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourcePlan");

                    b.Navigation("Topo");
                });

            modelBuilder.Entity("Sapphire2026.Data.Models.Diamond.DiamondTemporaryLimit", b =>
                {
                    b.HasOne("Sapphire2026.Data.Models.Diamond.DiamondTopoDocument", "Topo")
                        .WithMany()
                        .HasForeignKey("TopoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topo");
                });
#pragma warning restore 612, 618
        }
    }
}
