GET https://material.trensfm.com:5031/api/sapphireauthentication/version

GET https://material.trensfm.com:5031/api/sapphireauthentication/ping

PUT https://material.trensfm.com:5031/tourmaline/sapphireauthentication/userlogin
Content-Type: application/json

{
 "userName": "usuario",
 "password": "contraseña"
}






