<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\source\repos\FreeTrainSimulator.Models\FreeTrainSimulator.Models.csproj" />
    <ProjectReference Include="..\FreeTrainSimulator.Common\FreeTrainSimulator.Common.csproj" />
    <ProjectReference Include="..\Orts.Formats\Orts.Formats.csproj" />
  </ItemGroup>

</Project>
