<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release;TimeNet</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TreeView\Browser\**" />
    <Content Remove="TreeView\Browser\**" />
    <EmbeddedResource Remove="TreeView\Browser\**" />
    <None Remove="TreeView\Browser\**" />
  </ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimeNet2026\TimeNet2026.csproj" />
  </ItemGroup>

</Project>
