<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diamond\Diamond.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BlazorMonaco" Version="3.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Samples\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
