<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Zafiro</Configurations>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.13">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.13" />
		<PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.1" />
		<PackageReference Include="MySqlConnector" Version="2.5.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Sapphire2025Models\Sapphire2025Models.csproj" />
	  <ProjectReference Include="..\Diamond\Diamond.csproj" />
	</ItemGroup>
</Project>
