<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;TimeNet;Zafiro</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sapphire2025Models\Sapphire2025Models.csproj" />
    <ProjectReference Include="..\Sapphire25\Sapphire2026Data\Sapphire2026Data.csproj" />
    <ProjectReference Include="..\Sapphire25\TimeNet2026\TimeNet2026.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Images\PairingScreen.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
