<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GetText.NET" Version="10.0.1" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.4.1" />
    <PackageReference Include="NuGet.Versioning" Version="7.3.0" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.5" />
    <PackageReference Include="System.Management" Version="10.0.5" />
  </ItemGroup>

</Project>
