<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Zafiro</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Project\" />
    <Folder Include="Timed\" />
    <Folder Include="Topo\" />
  </ItemGroup>

</Project>
